# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# plugins=(autojump rails3 git ruby brew bundler rvm)
plugins=(autojump git osx)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

### Added by the Heroku Toolbelt
export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
export ANDROID_SDK="/Users/paulononaka/adt-bundle-mac-x86_64-20131030/sdk/"
export ANDROID_NDK="/Users/paulononaka/android-ndk-r9c"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$PATH:$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$ANDROID_NDK"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export CASSANDRA_HOME="/Users/paulononaka/codes/ufmg/apache-cassandra-2.1.1"
export TITAN_HOME="/Users/paulononaka/codes/ufmg/titan-0.5.1-hadoop2"
export JAVA_OPTIONS="-javaagent:$TITAN_HOME/lib/jamm-0.2.5.jar"
export JAVA_OPTS=$JAVA_OPTIONS

ulimit -c unlimited
